baseurl = "/"
languageCode = "en-us"
languageLang = "en"
title = "Let Us Eat"
copyright = "Melania Manestar © 2020 - 2020. All rights reserved."

# RSS, categories and tags disabled for an easy start
# See configuration options for more details: 
# https://gohugo.io/getting-started/configuration/#toml-configuration
disableKinds = ["taxonomy", "taxonomyTerm"]
disqusShortname = "blogComments"

[author]
name = "Melania Manestar"
email = "contact@letuseat.life"

[[menu.main]]
URL = "/"
name = "Home"
identiifer = ""
weight = 1

[[menu.main]]
URL = "/blog"
name = "Blog"
identiifer = "blog"
weight = 2

[[menu.main]]
URL = "/about"
name = "About"
identiifer = "about me"
weight = 3

[[menu.main]]
URL = "/subscribe"
name = "Subscribe"
identiifer = "subscribe"
weight = 4

[[menu.main]]
URL = "/contact"
name = "Contact"
identiifer = "contact"
weight = 5

#Site parameters
[params]
logo = "img/textletuseatlogo.svg"

# css plugins
[[params.plugins.css]]
URL = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
URL = "plugins/slick/slick.css"
[[params.plugins.css]]
URL = "plugins/themify-icons/themify-icons.css"


# js plugin
[[params.plugins.js]]
URL = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
URL = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
URL = "plugins/slick/slick.min.js"
[[params.plugins.js]]
URL = "plugins/shuffle/shuffle.min.js"
